version: '3.9'

services:
  challenge:
    build:
      context: ./server/challenge
      dockerfile: Dockerfile
    image: challenge-service:1.0.0
    ports:
      - 5001:5001

  essay:
    build:
      context: ./server/essay
      dockerfile: Dockerfile
    image: essay-service:1.0.0
    ports:
      - 5006:5006

  word:
    build:
      context: ./server/word
      dockerfile: Dockerfile
    image: word-service:1.0.0
    ports:
      - 5007:5007

  user:
    build:
      context: ./server/user
      dockerfile: Dockerfile
    image: user-service:1.0.0
    ports:
      - 5010:5010

  nut:
    build:
      context: ./server/nut
      dockerfile: Dockerfile
    image: nut-service:1.0.0
    ports:
      - 5011:5011
