apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: wordtree
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5010
---
apiVersion: v1
kind: Service
metadata:
  name: challenge-service
  namespace: wordtree
spec:
  type: ClusterIP
  selector:
    app: challenge-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: nut-service
  namespace: wordtree
spec:
  type: ClusterIP
  selector:
    app: nut-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5011
---
apiVersion: v1
kind: Service
metadata:
  name: word-service
  namespace: wordtree
spec:
  type: ClusterIP
  selector:
    app: word-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5007
---
apiVersion: v1
kind: Service
metadata:
  name: essay-service
  namespace: wordtree
spec:
  type: ClusterIP
  selector:
    app: essay-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5006
      