apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: wordtree
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5010
---
apiVersion: v1
kind: Service
metadata:
  name: challenge-service
  namespace: wordtree
spec:
  selector:
    app: challenge-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: nut-service
  namespace: wordtree
spec:
  selector:
    app: nut-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5011
---
apiVersion: v1
kind: Service
metadata:
  name: word-service
  namespace: wordtree
spec:
  selector:
    app: word-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5007
---
apiVersion: v1
kind: Service
metadata:
  name: essay-service
  namespace: wordtree
spec:
  selector:
    app: essay-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5006
---
apiVersion: v1
kind: Service
metadata:
  name: community-service
  namespace: wordtree
spec:
  selector:
    app: community-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5015
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: wordtree
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: wordtree
spec:
  selector:
    app: notification-service
  ports:
    - name: express
      protocol: TCP
      port: 8080
      targetPort: 5016
    - name: socket
      protocol: TCP
      port: 8081
      targetPort: 5017
